//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiktokLiveRec.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiktokLiveRec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Room 的本地化字符串。
        /// </summary>
        public static string AddRoom {
            get {
                return ResourceManager.GetString("AddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The live room {0} has been added 的本地化字符串。
        /// </summary>
        public static string AddRoomErrorDuplicated {
            get {
                return ResourceManager.GetString("AddRoomErrorDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully added {0} live room 的本地化字符串。
        /// </summary>
        public static string AddRoomSucc {
            get {
                return ResourceManager.GetString("AddRoomSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance Settings 的本地化字符串。
        /// </summary>
        public static string AppearanceSettings {
            get {
                return ResourceManager.GetString("AppearanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Shutdown 的本地化字符串。
        /// </summary>
        public static string AutoShutdown {
            get {
                return ResourceManager.GetString("AutoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto shutdown when unrecording 的本地化字符串。
        /// </summary>
        public static string AutoShutdownHint {
            get {
                return ResourceManager.GetString("AutoShutdownHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System will be auto shutdown in 1 minute 的本地化字符串。
        /// </summary>
        public static string AutoShutdownInTime {
            get {
                return ResourceManager.GetString("AutoShutdownInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Shutdown Time (HH:MM) 的本地化字符串。
        /// </summary>
        public static string AutoShutdownTime {
            get {
                return ResourceManager.GetString("AutoShutdownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avatar 的本地化字符串。
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string ButtonOfAdd {
            get {
                return ResourceManager.GetString("ButtonOfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ButtonOfCancel {
            get {
                return ResourceManager.GetString("ButtonOfCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string ButtonOfClose {
            get {
                return ResourceManager.GetString("ButtonOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Now 的本地化字符串。
        /// </summary>
        public static string ButtonOfCreateNow {
            get {
                return ResourceManager.GetString("ButtonOfCreateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto 的本地化字符串。
        /// </summary>
        public static string ButtonOfGoto {
            get {
                return ResourceManager.GetString("ButtonOfGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don’t show again 的本地化字符串。
        /// </summary>
        public static string ButtonOfOffRemind {
            get {
                return ResourceManager.GetString("ButtonOfOffRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string ButtonOfPlay {
            get {
                return ResourceManager.GetString("ButtonOfPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string ButtonOfSettings {
            get {
                return ResourceManager.GetString("ButtonOfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string CheckConnectivity {
            get {
                return ResourceManager.GetString("CheckConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running in the background 的本地化字符串。
        /// </summary>
        public static string CloseToTrayHint {
            get {
                return ResourceManager.GetString("CloseToTrayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coming soon 的本地化字符串。
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut 的本地化字符串。
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Desktop Shortcut 的本地化字符串。
        /// </summary>
        public static string CreateDesktopShortcutHint {
            get {
                return ResourceManager.GetString("CreateDesktopShortcutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No live room added~ 的本地化字符串。
        /// </summary>
        public static string EmptyRoomHint {
            get {
                return ResourceManager.GetString("EmptyRoomHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Recording 的本地化字符串。
        /// </summary>
        public static string EnableRecord {
            get {
                return ResourceManager.GetString("EnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether live streaming recording is enabled 的本地化字符串。
        /// </summary>
        public static string EnableRecordHint {
            get {
                return ResourceManager.GetString("EnableRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter room URL 的本地化字符串。
        /// </summary>
        public static string EnterRoomUrl {
            get {
                return ResourceManager.GetString("EnterRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect live room URL 的本地化字符串。
        /// </summary>
        public static string ErrorRoomUrl {
            get {
                return ResourceManager.GetString("ErrorRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed 的本地化字符串。
        /// </summary>
        public static string FailOp {
            get {
                return ResourceManager.GetString("FailOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get information about the live room 的本地化字符串。
        /// </summary>
        public static string GetRoomInfoError {
            get {
                return ResourceManager.GetString("GetRoomInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto Live Room 的本地化字符串。
        /// </summary>
        public static string GotoLiveRoom {
            get {
                return ResourceManager.GetString("GotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to get it? 的本地化字符串。
        /// </summary>
        public static string HowToGet {
            get {
                return ResourceManager.GetString("HowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Windows System Awake 的本地化字符串。
        /// </summary>
        public static string KeepActiveHint {
            get {
                return ResourceManager.GetString("KeepActiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Awake 的本地化字符串。
        /// </summary>
        public static string KeepAwake {
            get {
                return ResourceManager.GetString("KeepAwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default follows the system language 的本地化字符串。
        /// </summary>
        public static string LanguageHint {
            get {
                return ResourceManager.GetString("LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Notification 的本地化字符串。
        /// </summary>
        public static string LiveNotification {
            get {
                return ResourceManager.GetString("LiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to notify the start of the streaming through Windows system notifications, etc 的本地化字符串。
        /// </summary>
        public static string LiveNotificationHint {
            get {
                return ResourceManager.GetString("LiveNotificationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto goto Live Room 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToGotoLiveRoom {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto mute 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToGotoLiveRoomAndMute {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoomAndMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification via E-mail 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToMail {
            get {
                return ResourceManager.GetString("LiveNotificationToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification via playing music 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToPlayMusic {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use built-in music or specify music file path 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToPlayMusicPath {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification via Windows System 的本地化字符串。
        /// </summary>
        public static string LiveNotificationToSystem {
            get {
                return ResourceManager.GetString("LiveNotificationToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Room 的本地化字符串。
        /// </summary>
        public static string LiveRoom {
            get {
                return ResourceManager.GetString("LiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long Running Settings 的本地化字符串。
        /// </summary>
        public static string LongRunningSettings {
            get {
                return ResourceManager.GetString("LongRunningSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto {0}&apos;s live room immediately 的本地化字符串。
        /// </summary>
        public static string MailBodyElement {
            get {
                return ResourceManager.GetString("MailBodyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Settings 的本地化字符串。
        /// </summary>
        public static string NetworkSettings {
            get {
                return ResourceManager.GetString("NetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are currently no recording tasks 的本地化字符串。
        /// </summary>
        public static string NoRecordTask {
            get {
                return ResourceManager.GetString("NoRecordTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not supported in recording mode 的本地化字符串。
        /// </summary>
        public static string NotSupportedOnRecording {
            get {
                return ResourceManager.GetString("NotSupportedOnRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player 的本地化字符串。
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File ffplay not found so cannot be played! 的本地化字符串。
        /// </summary>
        public static string PlayerErrorOfFFplayNotFound {
            get {
                return ResourceManager.GetString("PlayerErrorOfFFplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No playable recording file 的本地化字符串。
        /// </summary>
        public static string PlayerErrorOfNoFile {
            get {
                return ResourceManager.GetString("PlayerErrorOfNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-in player 的本地化字符串。
        /// </summary>
        public static string PlayerInner {
            get {
                return ResourceManager.GetString("PlayerInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use FFplay player 的本地化字符串。
        /// </summary>
        public static string PlayerInnerHint {
            get {
                return ResourceManager.GetString("PlayerInnerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable reacangle window 的本地化字符串。
        /// </summary>
        public static string PlayerInnerUseRect {
            get {
                return ResourceManager.GetString("PlayerInnerUseRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System player 的本地化字符串。
        /// </summary>
        public static string PlayerSystem {
            get {
                return ResourceManager.GetString("PlayerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use System player 的本地化字符串。
        /// </summary>
        public static string PlayerSystemHint {
            get {
                return ResourceManager.GetString("PlayerSystemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Recording 的本地化字符串。
        /// </summary>
        public static string PlayRecord {
            get {
                return ResourceManager.GetString("PlayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support to play the recording videos 的本地化字符串。
        /// </summary>
        public static string PlayRecordHint {
            get {
                return ResourceManager.GetString("PlayRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL cannot be empty 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfEmptyUrl {
            get {
                return ResourceManager.GetString("ProxyErrorOfEmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid proxy or request failed: {0} 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfExceptionMessage {
            get {
                return ResourceManager.GetString("ProxyErrorOfExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL is malformed 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfFormat {
            get {
                return ResourceManager.GetString("ProxyErrorOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL host format is incorrect 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfHostFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfHostFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL missing hostname or port number 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfMissHostOrPort {
            get {
                return ResourceManager.GetString("ProxyErrorOfMissHostOrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL port number format is incorrect 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfPortFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy URL port number out of range 的本地化字符串。
        /// </summary>
        public static string ProxyErrorOfPortOutOfRange {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host name and port number 的本地化字符串。
        /// </summary>
        public static string ProxyHostAndPort {
            get {
                return ResourceManager.GetString("ProxyHostAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy available, response status code {0} 的本地化字符串。
        /// </summary>
        public static string ProxySuccOfStatusCode {
            get {
                return ResourceManager.GetString("ProxySuccOfStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Format 的本地化字符串。
        /// </summary>
        public static string RecordFormat {
            get {
                return ResourceManager.GetString("RecordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to auto delete the original TS/FLV file after converting the format 的本地化字符串。
        /// </summary>
        public static string RecordFormatAutoRemove {
            get {
                return ResourceManager.GetString("RecordFormatAutoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To ensure stable recording, only supports TS/FLV or will be auto converted later 的本地化字符串。
        /// </summary>
        public static string RecordFormatHint {
            get {
                return ResourceManager.GetString("RecordFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Log 的本地化字符串。
        /// </summary>
        public static string RecordLog {
            get {
                return ResourceManager.GetString("RecordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Settings 的本地化字符串。
        /// </summary>
        public static string RecordSettings {
            get {
                return ResourceManager.GetString("RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Status 的本地化字符串。
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfDisabled {
            get {
                return ResourceManager.GetString("RecordStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfError {
            get {
                return ResourceManager.GetString("RecordStatusOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfInitialized {
            get {
                return ResourceManager.GetString("RecordStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Recording 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfNotRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfNotRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string RecordStatusOfUnknown {
            get {
                return ResourceManager.GetString("RecordStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Room 的本地化字符串。
        /// </summary>
        public static string RemoveRoom {
            get {
                return ResourceManager.GetString("RemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle Period 的本地化字符串。
        /// </summary>
        public static string RoutineInterval {
            get {
                return ResourceManager.GetString("RoutineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cycle period (ms) for detecting the status and other actions 的本地化字符串。
        /// </summary>
        public static string RoutineIntervalHint {
            get {
                return ResourceManager.GetString("RoutineIntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down Room 的本地化字符串。
        /// </summary>
        public static string RowDownRoom {
            get {
                return ResourceManager.GetString("RowDownRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up Room 的本地化字符串。
        /// </summary>
        public static string RowUpRoom {
            get {
                return ResourceManager.GetString("RowUpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Folder 的本地化字符串。
        /// </summary>
        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is the saving directory distinguished by authors 的本地化字符串。
        /// </summary>
        public static string SaveFolderDistinguishedByAuthors {
            get {
                return ResourceManager.GetString("SaveFolderDistinguishedByAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the saving directory of recorded videos 的本地化字符串。
        /// </summary>
        public static string SaveFolderHint {
            get {
                return ResourceManager.GetString("SaveFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings File 的本地化字符串。
        /// </summary>
        public static string SettingsFile {
            get {
                return ResourceManager.GetString("SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Settings 的本地化字符串。
        /// </summary>
        public static string SingleSettings {
            get {
                return ResourceManager.GetString("SingleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string StatusOff {
            get {
                return ResourceManager.GetString("StatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string StatusOn {
            get {
                return ResourceManager.GetString("StatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Recording 的本地化字符串。
        /// </summary>
        public static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Streaming Status 的本地化字符串。
        /// </summary>
        public static string StreamStatus {
            get {
                return ResourceManager.GetString("StreamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string StreamStatusOfDisabled {
            get {
                return ResourceManager.GetString("StreamStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized 的本地化字符串。
        /// </summary>
        public static string StreamStatusOfInitialized {
            get {
                return ResourceManager.GetString("StreamStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Streaming 的本地化字符串。
        /// </summary>
        public static string StreamStatusOfNotStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfNotStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Streaming 的本地化字符串。
        /// </summary>
        public static string StreamStatusOfStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string StreamStatusOfUnknown {
            get {
                return ResourceManager.GetString("StreamStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation successful 的本地化字符串。
        /// </summary>
        public static string SuccOp {
            get {
                return ResourceManager.GetString("SuccOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording is in progress. Are you sure you want to continue your operation? 的本地化字符串。
        /// </summary>
        public static string SureOnRecording {
            get {
                return ResourceManager.GetString("SureOnRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete {0} live room? 的本地化字符串。
        /// </summary>
        public static string SureRemoveRoom {
            get {
                return ResourceManager.GetString("SureRemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does it stop the recording of {0}? 的本地化字符串。
        /// </summary>
        public static string SureStopRecord {
            get {
                return ResourceManager.GetString("SureStopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Color 的本地化字符串。
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a theme color you like 的本地化字符串。
        /// </summary>
        public static string ThemeColorHint {
            get {
                return ResourceManager.GetString("ThemeColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string ThemeOfDarkMode {
            get {
                return ResourceManager.GetString("ThemeOfDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string ThemeOfLightMode {
            get {
                return ResourceManager.GetString("ThemeOfLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TiktokLiveRec - Live Streaming Recorder 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string TrackingSystem {
            get {
                return ResourceManager.GetString("TrackingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Run (&amp;A) 的本地化字符串。
        /// </summary>
        public static string TrayMenuAutoRun {
            get {
                return ResourceManager.GetString("TrayMenuAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit (&amp;E) 的本地化字符串。
        /// </summary>
        public static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings (&amp;S) 的本地化字符串。
        /// </summary>
        public static string TrayMenuOpenSettings {
            get {
                return ResourceManager.GetString("TrayMenuOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart (&amp;R) 的本地化字符串。
        /// </summary>
        public static string TrayMenuRestart {
            get {
                return ResourceManager.GetString("TrayMenuRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show (&amp;V) 的本地化字符串。
        /// </summary>
        public static string TrayMenuShowMainWindow {
            get {
                return ResourceManager.GetString("TrayMenuShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tray Icon 的本地化字符串。
        /// </summary>
        public static string TrayStatus {
            get {
                return ResourceManager.GetString("TrayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable tray icon is following to recording status 的本地化字符串。
        /// </summary>
        public static string TrayStatusHint {
            get {
                return ResourceManager.GetString("TrayStatusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Cookie 的本地化字符串。
        /// </summary>
        public static string UseCookie {
            get {
                return ResourceManager.GetString("UseCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave blank to use built-in cookies 的本地化字符串。
        /// </summary>
        public static string UseCookieEnterHint {
            get {
                return ResourceManager.GetString("UseCookieEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Douyin requires cookies 的本地化字符串。
        /// </summary>
        public static string UseCookieHint {
            get {
                return ResourceManager.GetString("UseCookieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Douyin Cookie 的本地化字符串。
        /// </summary>
        public static string UseCookieOfDouyin {
            get {
                return ResourceManager.GetString("UseCookieOfDouyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tiktok Cookie 的本地化字符串。
        /// </summary>
        public static string UseCookieOfOversea {
            get {
                return ResourceManager.GetString("UseCookieOfOversea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Proxy 的本地化字符串。
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify your web proxy URL 的本地化字符串。
        /// </summary>
        public static string UseProxyHint {
            get {
                return ResourceManager.GetString("UseProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser UserAgent 的本地化字符串。
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave blank to use the built-in browser UserAgent 的本地化字符串。
        /// </summary>
        public static string UserAgentEnterHint {
            get {
                return ResourceManager.GetString("UserAgentEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can use a custom browser UserAgent 的本地化字符串。
        /// </summary>
        public static string UserAgentHint {
            get {
                return ResourceManager.GetString("UserAgentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
