//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiktokLiveRec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiktokLiveRec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddRoom {
            get {
                return ResourceManager.GetString("AddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddRoomSucc {
            get {
                return ResourceManager.GetString("AddRoomSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AppearanceSettings {
            get {
                return ResourceManager.GetString("AppearanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButtonOfAdd {
            get {
                return ResourceManager.GetString("ButtonOfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButtonOfClose {
            get {
                return ResourceManager.GetString("ButtonOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButtonOfGoto {
            get {
                return ResourceManager.GetString("ButtonOfGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButtonOfPlay {
            get {
                return ResourceManager.GetString("ButtonOfPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ButtonOfSettings {
            get {
                return ResourceManager.GetString("ButtonOfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckConnectivity {
            get {
                return ResourceManager.GetString("CheckConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnableRecord {
            get {
                return ResourceManager.GetString("EnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnableRecordHint {
            get {
                return ResourceManager.GetString("EnableRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnterRoomUrl {
            get {
                return ResourceManager.GetString("EnterRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorRoomUrl {
            get {
                return ResourceManager.GetString("ErrorRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FailOp {
            get {
                return ResourceManager.GetString("FailOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetRoomInfoError {
            get {
                return ResourceManager.GetString("GetRoomInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Live Room.
        /// </summary>
        public static string GotoLiveRoom {
            get {
                return ResourceManager.GetString("GotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowToGet {
            get {
                return ResourceManager.GetString("HowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LanguageHint {
            get {
                return ResourceManager.GetString("LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Notification.
        /// </summary>
        public static string LiveNotification {
            get {
                return ResourceManager.GetString("LiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationHint {
            get {
                return ResourceManager.GetString("LiveNotificationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToGotoLiveRoom {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToGotoLiveRoomAndMute {
            get {
                return ResourceManager.GetString("LiveNotificationToGotoLiveRoomAndMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToMail {
            get {
                return ResourceManager.GetString("LiveNotificationToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToPlayMusic {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToPlayMusicPath {
            get {
                return ResourceManager.GetString("LiveNotificationToPlayMusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveNotificationToSystem {
            get {
                return ResourceManager.GetString("LiveNotificationToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LiveRoom {
            get {
                return ResourceManager.GetString("LiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto {0}&apos;s live room immediately.
        /// </summary>
        public static string MailBodyElement {
            get {
                return ResourceManager.GetString("MailBodyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NetworkSettings {
            get {
                return ResourceManager.GetString("NetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoRecordTask {
            get {
                return ResourceManager.GetString("NoRecordTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Opration {
            get {
                return ResourceManager.GetString("Opration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ffplay not found so cannot be played!.
        /// </summary>
        public static string PlayerErrorOfFFplayNotFound {
            get {
                return ResourceManager.GetString("PlayerErrorOfFFplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerErrorOfNoFile {
            get {
                return ResourceManager.GetString("PlayerErrorOfNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerInner {
            get {
                return ResourceManager.GetString("PlayerInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerInnerHint {
            get {
                return ResourceManager.GetString("PlayerInnerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerInnerUseRect {
            get {
                return ResourceManager.GetString("PlayerInnerUseRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerSystem {
            get {
                return ResourceManager.GetString("PlayerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayerSystemHint {
            get {
                return ResourceManager.GetString("PlayerSystemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayRecord {
            get {
                return ResourceManager.GetString("PlayRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlayRecordHint {
            get {
                return ResourceManager.GetString("PlayRecordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfEmptyUrl {
            get {
                return ResourceManager.GetString("ProxyErrorOfEmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfExceptionMessage {
            get {
                return ResourceManager.GetString("ProxyErrorOfExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfFormat {
            get {
                return ResourceManager.GetString("ProxyErrorOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfHostFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfHostFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfMissHostOrPort {
            get {
                return ResourceManager.GetString("ProxyErrorOfMissHostOrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfPortFormatError {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyErrorOfPortOutOfRange {
            get {
                return ResourceManager.GetString("ProxyErrorOfPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxyHostAndPort {
            get {
                return ResourceManager.GetString("ProxyHostAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProxySuccOfStatusCode {
            get {
                return ResourceManager.GetString("ProxySuccOfStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordFormat {
            get {
                return ResourceManager.GetString("RecordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordFormatAutoRemove {
            get {
                return ResourceManager.GetString("RecordFormatAutoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordFormatHint {
            get {
                return ResourceManager.GetString("RecordFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordLog {
            get {
                return ResourceManager.GetString("RecordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordSettings {
            get {
                return ResourceManager.GetString("RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfDisabled {
            get {
                return ResourceManager.GetString("RecordStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfError {
            get {
                return ResourceManager.GetString("RecordStatusOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfInitialized {
            get {
                return ResourceManager.GetString("RecordStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfNotRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfNotRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfRecording {
            get {
                return ResourceManager.GetString("RecordStatusOfRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecordStatusOfUnknown {
            get {
                return ResourceManager.GetString("RecordStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveRoom {
            get {
                return ResourceManager.GetString("RemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoutineInterval {
            get {
                return ResourceManager.GetString("RoutineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoutineIntervalHint {
            get {
                return ResourceManager.GetString("RoutineIntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowDownRoom {
            get {
                return ResourceManager.GetString("RowDownRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowUpRoom {
            get {
                return ResourceManager.GetString("RowUpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveFolderHint {
            get {
                return ResourceManager.GetString("SaveFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsFile {
            get {
                return ResourceManager.GetString("SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SingleSettings {
            get {
                return ResourceManager.GetString("SingleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatus {
            get {
                return ResourceManager.GetString("StreamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatusOfDisabled {
            get {
                return ResourceManager.GetString("StreamStatusOfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatusOfInitialized {
            get {
                return ResourceManager.GetString("StreamStatusOfInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatusOfNotStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfNotStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatusOfStreaming {
            get {
                return ResourceManager.GetString("StreamStatusOfStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreamStatusOfUnknown {
            get {
                return ResourceManager.GetString("StreamStatusOfUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SuccOp {
            get {
                return ResourceManager.GetString("SuccOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SureRemoveRoom {
            get {
                return ResourceManager.GetString("SureRemoveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SureStopRecord {
            get {
                return ResourceManager.GetString("SureStopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ThemeColorHint {
            get {
                return ResourceManager.GetString("ThemeColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ThemeOfDarkMode {
            get {
                return ResourceManager.GetString("ThemeOfDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ThemeOfLightMode {
            get {
                return ResourceManager.GetString("ThemeOfLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrackingSystem {
            get {
                return ResourceManager.GetString("TrackingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayMenuAutoRun {
            get {
                return ResourceManager.GetString("TrayMenuAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayMenuOpenSettings {
            get {
                return ResourceManager.GetString("TrayMenuOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayMenuRestart {
            get {
                return ResourceManager.GetString("TrayMenuRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayMenuShowMainWindow {
            get {
                return ResourceManager.GetString("TrayMenuShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayStatus {
            get {
                return ResourceManager.GetString("TrayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayStatusHint {
            get {
                return ResourceManager.GetString("TrayStatusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseCookie {
            get {
                return ResourceManager.GetString("UseCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseCookieEnterHint {
            get {
                return ResourceManager.GetString("UseCookieEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseCookieHint {
            get {
                return ResourceManager.GetString("UseCookieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseCookieOfDouyin {
            get {
                return ResourceManager.GetString("UseCookieOfDouyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseCookieOfOversea {
            get {
                return ResourceManager.GetString("UseCookieOfOversea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseProxyHint {
            get {
                return ResourceManager.GetString("UseProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserAgentEnterHint {
            get {
                return ResourceManager.GetString("UserAgentEnterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserAgentHint {
            get {
                return ResourceManager.GetString("UserAgentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
